name: "Build"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          xcodebuild -project QSS.xcodeproj \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED="NO" \
            CODE_SIGN_ENTITLEMENTS=""\
            CODE_SIGNING_ALLOWED="NO"